export const SITEINFO = {
    TITLE: "サイト名",
    DISCRIPTION: "Generated by create next app",
    HEADER_TYPE: "normal",
    FOOTER_TYPE: "none",
    MAIN_MENU: [
        {NAME: "Dashboard", PATH: "/"},
        {NAME: "Info", PATH: "/info"},
    ],
    SUB_MENU: [
        {NAME: "Your Profile", PATH: "/"},
        {NAME: "Settings", PATH: "/"},
        {NAME: "Sign out", PATH: "/"},
    ],
    SIDE_MENU: [
        {NAME: "Posts", PATH: "/posts"},
        {NAME: "Messages", PATH: "/messages"},
    ],

}